# The only door for checking out and for refunds. Everything in one transaction: sale, lines,
# payments and kardex; if anything fails, nothing is left half done.
module Till
  class Error < StandardError; end

  # The price rule stopped a line: nothing is checked out and the attempt is reported.
  class Stopped < Error
    attr_reader :report, :value_cents

    def initialize(message, report:, value_cents:)
      super(message)
      @report = report
      @value_cents = value_cents
    end
  end

  # lines:    [{ product_id:, quantity:, price_cents: }]
  # payments: [{ payment_method:, amount_cents: }]; the "credit" method goes on the customer's account.
  # key:      unique ticket identifier generated by the till; repeating the same key returns the same sale.
  # customer: who is buying (needed for selling on account).
  # order:    the order being checked out; what it reserved can be sold.
  # sold_at:  if the sale was made offline and is uploaded now, when it was made. The goods already
  # left, so nothing is stopped: whatever a rule would have stopped (or reserved stock, or the cash
  # limit) is recorded and reported. Nothing is sold on account offline.
  def self.checkout!(branch:, user:, lines:, payments:, key:, authorizer: nil, customer: nil, order: nil, sold_at: nil)
    raise Error, I18n.t("errors.till.key_ticket") if key.blank?
    if (existing = Sale.find_by(key: key))
      return existing
    end
    offline = sold_at.present?
    shift = Shift.opened_at(branch) or raise Error, I18n.t("errors.till.no_till", branch: branch.name)
    raise Error, I18n.t("errors.till.exceeds_limit", amount: Money.format_money(branch.cash_limit_cents)) if shift.exceeds_limit? && !offline
    raise Error, I18n.t("errors.till.ticket_empty") if lines.blank?

    code = Rule.current("price")&.code
    failures = [] # [text key, error] of the rules that blew up
    notices = [] # offline: what would have been stopped

    Sale.transaction do
      prepared = lines.map { |l| prepare_line(branch, l, authorizer, code, failures, offline) }
      begin
        Reservations.check!(branch, prepared.map { |l| [ l[:product], l[:quantity] ] }, except: order)
      rescue Reservations::Error => e
        raise unless offline
        notices << e.message
      end
      total = prepared.sum { |l| l[:amount_cents] }
      payments_ok = prepare_payments(payments, total)
      change = payments_ok.sum { |p| p[:amount_cents] } - total
      on_account = payments_ok.select { |p| p[:payment_method] == Payment::ON_ACCOUNT }.sum { |p| p[:amount_cents] }
      raise Error, I18n.t("errors.till.on_account_offline") if offline && on_account.positive?
      review_sale = judge_sale!(prepared, payments_ok, total, change, user, failures, offline)
      review_credit = judge_credit!(customer, on_account, total, user, failures) if on_account.positive?
      notices << I18n.t("till.offline_exceeds_limit") if offline && shift.exceeds_limit?
      review_sale = [ review_sale, *notices.map { |n| I18n.t("till.offline_notice", notice: n) } ].compact.join("\n").presence

      sale = Sale.create!(branch: branch, shift: shift, user: user, key: key, customer: customer,
                            folio: Folio.next_number!(branch, "sale"), code: ticket_code(branch),
                            total_cents: total, change_cents: change, business_date: (sold_at || Time.current).to_date,
                            offline: offline, sold_at: sold_at)
      prepared.each do |l|
        review, value = l.extract!(:review, :value_review).values_at(:review, :value_review)
        line = sale.lines.create!(l)
        Inventory.move!(branch: branch, product: line.product, kind: "sale", quantity: line.quantity,
                          user: user, reference: sale, reason: sale.folio)
        Review.open!(line, user: user, branch: branch, reason: review, value_cents: value) if review
      end
      payments_ok.each { |p| sale.payments.create!(p) }
      Review.open!(sale, user: user, branch: branch, reason: review_sale, value_cents: total) if review_sale
      if on_account.positive?
        customer.credit_movements.create!(kind: "charge", amount_cents: on_account, date: Date.current, reference: sale, branch: branch,
                                            user: user, reason: I18n.t("customers.account.charge_sale", folio: sale.folio))
        Review.open!(sale, user: user, branch: branch, reason: review_credit, value_cents: on_account) if review_credit
      end
      # If the business's rule blew up, the built-in one decided; the failure is reported once per shift.
      failures.uniq.each { |text_key, error| Review.open!(shift, user: user, branch: branch, reason: I18n.t(text_key, error: error), no_repeat: true) }
      sale
    end
  rescue Inventory::OutOfStock, Reservations::Error => e
    raise Error, I18n.t("errors.till.cannot_sell_without", message: e.message)
  rescue Stopped => e
    Review.open!(shift, user: user, branch: branch, reason: e.report, value_cents: e.value_cents, stopped: true)
    raise
  end

  # lines: [{ sale_line_id:, quantity: }]. The money comes out of the open shift's drawer; if the
  # sale was on account, it first lowers what the customer owes on it and only the rest goes out in cash.
  def self.refund!(sale:, lines:, reason:, user:)
    raise Error, I18n.t("errors.reason_required") if reason.blank?
    raise Error, I18n.t("errors.till.already_refunded") unless sale.paid?
    shift = Shift.opened_at(sale.branch) or raise Error, I18n.t("errors.till.no_till_refund")
    raise Error, I18n.t("errors.till.nothing_refunded") if lines.blank?

    Sale.transaction do
      refund = Refund.new(sale: sale, shift: shift, user: user, reason: reason, total_cents: 0)
      total = 0
      lines.each do |l|
        sale_line = sale.lines.find(l[:sale_line_id])
        quantity = BigDecimal(l[:quantity].to_s).round(3)
        raise Error, I18n.t("errors.till.max_refund", product: sale_line.product.name, max: sale_line.pending_quantity.to_s("F")) if quantity <= 0 || quantity > sale_line.pending_quantity
        amount = Money.amount(quantity, sale_line.price_cents)
        total += amount
        refund.lines.build(sale_line: sale_line, quantity: quantity, amount_cents: amount)
        Inventory.move!(branch: sale.branch, product: sale_line.product, kind: "customer_return", quantity: quantity,
                          user: user, reference: refund, reason: "#{sale.folio}: #{reason}")
      end
      refund.total_cents = total
      refund.on_account_cents = [ total, sale.on_account_pending_cents ].min if sale.customer
      refund.save!
      if refund.on_account_cents.positive?
        sale.customer.credit_movements.create!(kind: "refund", amount_cents: -refund.on_account_cents, date: Date.current, reference: refund,
                                                  branch: sale.branch, user: user, reason: I18n.t("customers.account.refund", folio: sale.folio))
      end
      sale.update!(status: "refunded") if sale.lines.all? { |sl| sl.reload.pending_quantity.zero? }
      refund
    end
  end

  def self.prepare_line(branch, l, authorizer, code, failures, offline = false)
    product = Product.active.find(l[:product_id])
    quantity = BigDecimal(l[:quantity].to_s).round(3)
    raise Error, I18n.t("errors.till.invalid_quantity", product: product.name) unless quantity.positive?
    raise Error, I18n.t("errors.till.whole_pieces", product: product.name) if !product.fractional? && quantity != quantity.floor
    catalog = product.price_cents_for(branch)
    # A new product reaches the store without a price: it can be received, but not sold until it has one.
    raise Error, I18n.t("errors.till.no_price", product: product.name, branch: branch.name) unless catalog.positive?
    promo_price, promotion = Promotion.best(product, branch, quantity, catalog)
    regular = promo_price || catalog
    price = l[:price_cents].present? ? l[:price_cents].to_i : regular
    if price < regular
      floor = Setting.integer("till.price_floor") / 100.0 # never below the floor, not with permission nor with a rule
      raise Error, I18n.t("errors.till.price_floor", product: product.name, floor: Setting.integer("till.price_floor"), amount: Money.format_money((catalog * floor).ceil)) if price < catalog * floor
    end
    # The price rule decides the rest. If it stops and whoever authorizes has till.lower_price, it
    # goes through under their name but stays pending review: nobody is left unable to sell.
    authorized = authorizer&.can?("till.lower_price") || false
    data = PriceRule::Input.new(product: product, quantity: quantity, price: price, catalog: catalog, regular: regular, authorized: authorized)
    decision = PriceRule.decide(data, code: code)
    failures << [ "price_rule.failure", decision.error ] if decision.error
    line_text = I18n.t("till.price_line", product: product.name, price: Money.format_money(price), regular: Money.format_money(regular))
    value = Money.amount(quantity, [ regular - price, 0 ].max)
    if decision.rejects? && !authorized && !offline
      raise Stopped.new(I18n.t("errors.till.price_stopped", line: line_text, reason: decision.reason), report: "#{line_text}: #{decision.reason}", value_cents: value)
    end
    offline_would_stop = decision.rejects? && !authorized
    { product: product, quantity: quantity, price_cents: price, catalog_cents: catalog,
      amount_cents: Money.amount(quantity, price), authorized_by: (authorizer if authorized && price < regular),
      promotion: (price == promo_price ? promotion : nil),
      review: (decision.allows? ? nil : (offline_would_stop ? I18n.t("till.offline_notice", notice: "#{line_text}: #{decision.reason}") : "#{line_text}: #{decision.reason}")),
      value_review: value }
  end
  private_class_method :prepare_line

  # The whole sale, before checking it out, through the sales rule. If it stops and whoever checks
  # out does not have till.force_sale, it is not checked out and gets reported; otherwise returns
  # the reason to review it (or nil).
  def self.judge_sale!(prepared, payments, total, change, user, failures, offline = false)
    authorized = user.can?("till.force_sale")
    data = SaleRule.data(prepared, payments, total: total, change: change, authorized: authorized)
    decision = SaleRule.decide(data, code: Rule.current("sale")&.code)
    failures << [ "sale_rule.failure", decision.error ] if decision.error
    if decision.rejects? && !authorized
      return I18n.t("till.offline_notice", notice: decision.reason) if offline
      raise Stopped.new(I18n.t("errors.till.sale_stopped", reason: decision.reason), report: I18n.t("till.sale_stopped", total: Money.format_money(total), reason: decision.reason), value_cents: total)
    end
    decision.allows? ? nil : decision.reason
  end
  private_class_method :judge_sale!

  # On the customer's account, if the credit rule allows it. If it stops and whoever checks out
  # does not have customers.force_credit, it is not checked out and gets reported; otherwise returns
  # the reason to review it (or nil).
  def self.judge_credit!(customer, on_account, total, user, failures)
    raise Error, I18n.t("errors.till.on_account_no_customer") unless customer
    authorized = user.can?("customers.force_credit")
    decision = CreditRule.decide(CreditRule.data(customer, amount: on_account, total: total, authorized: authorized))
    failures << [ "credit_rule.failure", decision.error ] if decision.error
    if decision.rejects? && !authorized
      raise Stopped.new(I18n.t("errors.till.credit_stopped", reason: decision.reason),
                        report: I18n.t("till.credit_stopped", customer: customer.name, amount: Money.format_money(on_account), reason: decision.reason), value_cents: on_account)
    end
    decision.allows? ? nil : decision.reason
  end
  private_class_method :judge_credit!

  def self.prepare_payments(payments, total)
    clean = Array(payments).map { |p| { payment_method: p[:payment_method].to_s, amount_cents: p[:amount_cents].to_i } }.reject { |p| p[:amount_cents] <= 0 }
    clean.each { |p| raise Error, I18n.t("errors.till.unknown_payment_method", payment_method: p[:payment_method]) unless (Payment::PAYMENT_METHODS + [ Payment::ON_ACCOUNT ]).include?(p[:payment_method]) }
    sum = clean.sum { |p| p[:amount_cents] }
    raise Error, I18n.t("errors.till.missing_money", total: Money.format_money(total), payment: Money.format_money(sum)) if sum < total
    non_cash = clean.reject { |p| p[:payment_method] == "cash" }.sum { |p| p[:amount_cents] }
    raise Error, I18n.t("errors.till.non_cash_exceeds") if non_cash > total
    clean
  end
  private_class_method :prepare_payments

  def self.ticket_code(branch)
    sequence = Counter.next_number!("ticket:#{branch.id}")
    Barcode.ean13(format("09%02d%08d", branch.id % 100, sequence % 100_000_000))
  end
  private_class_method :ticket_code
end
